apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend
            image: mmartfl/backend:v2
            imagePullPolicy: IfNotPresent
            command: ["python", "get_data.py"]
          restartPolicy: OnFailure
